### ISSUE TITLE
undefined method '[]' for Nil:NilClass

### ISSUE THREAD

**Issue by Alonsorossi** [OpenSourcePolitics/decidim-module-homepage_interactive_map#56]
After creating an application on the HERE provider, configuring my secrets.yml file, and uncommenting the lines in the decidim.rb file, I installed the module as instructed in the documentation. I created an assembly and assigned it the scopes for geolocation. I activated it in the administration panel to be displayed on the homepage, but still, the map is not being shown to me.

I am working with Decidim 0.27.2 on a local development environment, and for the map provider, I chose HERE, which was recommended by the documentation.

**Comment by Alonsorossi** [comment]
Resolved

**Comment by paulinebessoles** [comment]
The 0.27.2 seems to have several fixes not implemented. 
![image](https://github.com/OpenSourcePolitics/decidim-module-homepage_interactive_map/assets/52420208/de04e225-597f-492c-b97c-1cb3c2d2b4e0)

**Comment by Alonsorossi** [comment]
I closed the issue because I was shown the map with the seeds of the module, but when trying to put my geojson it gives the error of undefined method '[]' for Nil:NilClass

**Comment by Quentinchampenois** [comment]
Hello @Alonsorossi, thank you for your issue ! 

Thanks to @paulinebessoles we have an idea of the cause and the solution, I will update the module ASAP !

**Comment by cdm-tao** [comment]
The problem is caused by incorrectly referencing Hash properties with strings/symbols.

One way to fix problem:
- In .\app\commands\decidim\admin\update_scope.rb, form.geojson properties should be referenced by string in geojson method.
- In .\app\forms\decidim\admin\scope_form.rb :parsed_geometry property of attribute :geoJson should be of type Hash, and in parsable_json method json should be parsed using symbols, not strings, as property names - ie JSON.parse(geometry, { symbolize_names: true })
